### PR TITLE
#3467: Add Jenkinsfile for Prod_Build_MailingListClient pipeline

### PR DESCRIPTION
**Pull request by kdp136**
Add Jenkinsfile to allow creation of pipeline

**Please ensure the following boxes are ticked before asking for a review (tick to show they've been considered even if no action is needed):**
- [x] Link to close related issues
- [x] Created any necessary tests (unit / integration / BLAATs)
- [x] All tests passing (unit / integration / BLAATs)
- [x] SQL rollout and rollback included and tested
- [x] Release information for end users included
- [x] Labelled appropriately (`BISAppSettings Change`, `DB`, `WSDL`)

### CODE REVIEW

**Review by dmbrownless — APPROVED** [review]

**Review by j4mes-4rgent — COMMENTED** [review]
Is this not being put in to a jenkinsfile directory?

**Comment by kdp136** [comment]
> Is this not being put in to a jenkinsfile directory?

It didn't seem necessary when there were only 2 jenkinsfiles to go in but I can move them into a new folder if you think it's needed?

**Comment by j4mes-4rgent** [comment]
> > Is this not being put in to a jenkinsfile directory?
> 
> It didn't seem necessary when there were only 2 jenkinsfiles to go in but I can move them into a new folder if you think it's needed?

I think we should future-proof it, and make it neater and more consistent with users

**Comment by kdp136** [comment]
> > > Is this not being put in to a jenkinsfile directory?
> > 
> > 
> > It didn't seem necessary when there were only 2 jenkinsfiles to go in but I can move them into a new folder if you think it's needed?
> 
> I think we should future-proof it, and make it neater and more consistent with users

No problem I'll make the changes now

**Review by j4mes-4rgent — APPROVED** [review]

**Pull request merged**
